version: '2'
services:
    selenium-hub:
        restart: always
        image: selenium/hub
        container_name: 'selenium-hub'
        ports:
            - '4444:4444'

    chrome:
        restart: always
        image: selenium/node-chrome-debug
        container_name: 'chrome'
        environment:
            - HUB_PORT_4444_TCP_ADDR=selenium-hub
            - HUB_PORT_4444_TCP_PORT=4444
        ports:
            - '5900:5900'
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub

    #firefox:
    #    restart: always
    #    image: selenium/node-firefox-debug
    #    container_name: 'firefox'
    #    ports:
    #        - '5910:5900'
    #    environment:
    #        - HUB_PORT_4444_TCP_ADDR=selenium-hub
    #        - HUB_PORT_4444_TCP_PORT=4444
    #    links:
    #        - selenium-hub:hub
    #    depends_on:
    #        - selenium-hub

    python:
        restart: always
        image: python:3
        container_name: 'python'
        working_dir: '/root/'
        command: 'tail -f /dev/null'
        volumes:
            - ./opt/:/root/opt/

    jenkins:
        restart: always
        image: reflet/docker-jenkins
        container_name: 'jenkins'
        working_dir: '/root/opt'
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins-data:/var/jenkins_home

volumes:
    jenkins-data:
        driver: local
